/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { InstantiateMsg, ExecuteMsg, Timestamp, Uint64, Uint128, Decimal, TokenUnverified, ProposalStatus, ProposalTypeForStringAndTokenUnverified, EmissionType, Binary, StakedCollectionInfoForString, StakedTokenInfo, ProposalForStringAndTokenUnverified, FundsForTokenUnverified, CurrencyForTokenUnverified, CollectionForStringAndTokenUnverified, Cw20ReceiveMsg, QueryMsg, MigrateMsg, Token, Addr, BalancesResponseItem, FundsForToken, CurrencyForToken, ArrayOfQueryCollectionsResponseItem, QueryCollectionsResponseItem, CollectionForAddrAndToken, ArrayOfQueryCollectionsBalancesResponseItem, QueryCollectionsBalancesResponseItem, Config, ArrayOfFundsForToken, ProposalTypeForAddrAndToken, ArrayOfQueryProposalsResponseItem, QueryProposalsResponseItem, ProposalForAddrAndToken, ArrayOfQueryStakersResponseItem, QueryStakersResponseItem, StakedCollectionInfoForAddr } from "./StakingPlatform.types";
export interface StakingPlatformMsg {
  contractAddress: string;
  sender: string;
  stake: ({
    collectionsToStake
  }: {
    collectionsToStake: StakedCollectionInfoForString[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  unstake: ({
    collectionsToUnstake
  }: {
    collectionsToUnstake: StakedCollectionInfoForString[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  claimStakingRewards: ({
    collection
  }: {
    collection?: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateConfig: ({
    minter,
    owner
  }: {
    minter?: string;
    owner?: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  distributeFunds: ({
    addressAndWeightList
  }: {
    addressAndWeightList: string[][];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  removeCollection: ({
    address
  }: {
    address: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  createProposal: ({
    proposal
  }: {
    proposal: ProposalForStringAndTokenUnverified;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  rejectProposal: ({
    id
  }: {
    id: Uint128;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  acceptProposal: ({
    id
  }: {
    id: Uint128;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  depositTokens: ({
    collectionAddress
  }: {
    collectionAddress: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  withdrawTokens: ({
    amount,
    collectionAddress
  }: {
    amount: Uint128;
    collectionAddress: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class StakingPlatformMsgComposer implements StakingPlatformMsg {
  sender: string;
  contractAddress: string;

  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.stake = this.stake.bind(this);
    this.unstake = this.unstake.bind(this);
    this.claimStakingRewards = this.claimStakingRewards.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
    this.distributeFunds = this.distributeFunds.bind(this);
    this.removeCollection = this.removeCollection.bind(this);
    this.createProposal = this.createProposal.bind(this);
    this.rejectProposal = this.rejectProposal.bind(this);
    this.acceptProposal = this.acceptProposal.bind(this);
    this.depositTokens = this.depositTokens.bind(this);
    this.withdrawTokens = this.withdrawTokens.bind(this);
    this.receive = this.receive.bind(this);
  }

  stake = ({
    collectionsToStake
  }: {
    collectionsToStake: StakedCollectionInfoForString[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          stake: {
            collections_to_stake: collectionsToStake
          }
        })),
        funds: _funds
      })
    };
  };
  unstake = ({
    collectionsToUnstake
  }: {
    collectionsToUnstake: StakedCollectionInfoForString[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          unstake: {
            collections_to_unstake: collectionsToUnstake
          }
        })),
        funds: _funds
      })
    };
  };
  claimStakingRewards = ({
    collection
  }: {
    collection?: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          claim_staking_rewards: {
            collection
          }
        })),
        funds: _funds
      })
    };
  };
  updateConfig = ({
    minter,
    owner
  }: {
    minter?: string;
    owner?: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_config: {
            minter,
            owner
          }
        })),
        funds: _funds
      })
    };
  };
  distributeFunds = ({
    addressAndWeightList
  }: {
    addressAndWeightList: string[][];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          distribute_funds: {
            address_and_weight_list: addressAndWeightList
          }
        })),
        funds: _funds
      })
    };
  };
  removeCollection = ({
    address
  }: {
    address: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          remove_collection: {
            address
          }
        })),
        funds: _funds
      })
    };
  };
  createProposal = ({
    proposal
  }: {
    proposal: ProposalForStringAndTokenUnverified;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_proposal: {
            proposal
          }
        })),
        funds: _funds
      })
    };
  };
  rejectProposal = ({
    id
  }: {
    id: Uint128;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          reject_proposal: {
            id
          }
        })),
        funds: _funds
      })
    };
  };
  acceptProposal = ({
    id
  }: {
    id: Uint128;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          accept_proposal: {
            id
          }
        })),
        funds: _funds
      })
    };
  };
  depositTokens = ({
    collectionAddress
  }: {
    collectionAddress: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          deposit_tokens: {
            collection_address: collectionAddress
          }
        })),
        funds: _funds
      })
    };
  };
  withdrawTokens = ({
    amount,
    collectionAddress
  }: {
    amount: Uint128;
    collectionAddress: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          withdraw_tokens: {
            amount,
            collection_address: collectionAddress
          }
        })),
        funds: _funds
      })
    };
  };
  receive = ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          receive: {
            amount,
            msg,
            sender
          }
        })),
        funds: _funds
      })
    };
  };
}