WASM_STARGAZE_MINTER="../../artifacts/minter.wasm"
WASM_STARGAZE_STAKING_PLATFORM="../../artifacts/staking_platform.wasm"
WASM_INJECTIVE_MINTER="../../artifacts/minter_inj.wasm"
WASM_INJECTIVE_STAKING_PLATFORM=$WASM_STARGAZE_STAKING_PLATFORM

WASM_SOURCE_STARGAZE_MINTER="https://github.com/cryptogopniks/GopStake/releases/tag/minter-v1.1.1"
WASM_SOURCE_STARGAZE_STAKING_PLATFORM="https://github.com/cryptogopniks/GopStake/releases/tag/staking_platform-v1.3.1"
WASM_SOURCE_INJECTIVE_MINTER="https://github.com/cryptogopniks/GopStake/releases/tag/minter_inj-v1.1.1"
WASM_SOURCE_INJECTIVE_STAKING_PLATFORM=$WASM_SOURCE_STARGAZE_STAKING_PLATFORM

HASH_SUM_STARGAZE_MINTER="7591410a254f1a381b509c7740c2f25a2859a7802900b4eacc430ccbc2967108"
HASH_SUM_STARGAZE_STAKING_PLATFORM="fdf63299a1abf865578dd6c74ac0c074c2d36d3cc05d356e16af7a7afc10a358"
HASH_SUM_INJECTIVE_MINTER="3ddf629061fb297f14edf22c54521f6cf544556a2473a0231c428cb32dd4b759"
HASH_SUM_INJECTIVE_STAKING_PLATFORM=$HASH_SUM_STARGAZE_STAKING_PLATFORM

TITLE_STARGAZE_MINTER="CryptoGopniks NFT Staking Platform: Minter Contract v.1.1.1"
TITLE_STARGAZE_STAKING_PLATFORM="CryptoGopniks NFT Staking Platform: Staking Platform Contract v.1.3.1"
TITLE_INJECTIVE_MINTER=$TITLE_STARGAZE_MINTER
TITLE_INJECTIVE_STAKING_PLATFORM=$TITLE_STARGAZE_STAKING_PLATFORM

DESCRIPTION_STARGAZE_MINTER=$(cat desc-sg-minter.md | jq -Rsa)
DESCRIPTION_STARGAZE_STAKING_PLATFORM=$(cat desc-sg-platform.md | jq -Rsa)
DESCRIPTION_INJECTIVE_MINTER=$(cat desc-inj-minter.md | jq -Rsa)
DESCRIPTION_INJECTIVE_STAKING_PLATFORM=$(cat desc-inj-platform.md | jq -Rsa)

CHAIN_ID_STARGAZE="stargaze-1"
CHAIN_ID_INJECTIVE="injective-1"

RPC_STARGAZE="https://stargaze-rpc.reece.sh:443"
RPC_INJECTIVE="https://injective-rpc.lavenderfive.com:443"

DAEMON_STARGAZE="starsd"
DAEMON_INJECTIVE="injectived"

ADDRESS_ADMIN_STARGAZE="stars1f37v0rdvrred27tlqqcpkrqpzfv6ddr2a97zzu"
ADDRESS_OWNER_STARGAZE="stars1hvp3q00ypzrurd46h7c7c3hu86tx9uf8sg5lm3"
ADDRESS_ADMIN_INJECTIVE="inj15wry0urr7d049m79299mzedax0zvtx9kc29umh"
ADDRESS_OWNER_INJECTIVE="inj1u9jles5s3nw29726frttn007h9880n2zyfwf6c"

DENOM_STARGAZE="ustars"
DENOM_INJECTIVE="inj"

DEPOSIT_STARGAZE="50000000000$DENOM_STARGAZE"
DEPOSIT_INJECTIVE="500000000$DENOM_INJECTIVE"

QFLAG_STARGAZE="--chain-id $CHAIN_ID_STARGAZE --node $RPC_STARGAZE"
TXFLAG_STARGAZE="-y --gas auto --gas-prices 1.2$DENOM_STARGAZE --gas-adjustment 1.3 $QFLAG_STARGAZE"
QFLAG_INJECTIVE="--chain-id $CHAIN_ID_INJECTIVE --node $RPC_INJECTIVE"
TXFLAG_INJECTIVE="-y --gas auto --gas-prices 900000000$DENOM_INJECTIVE --gas-adjustment 1.3 $QFLAG_INJECTIVE"

BUILDER="cargo-cw-optimizoor:0.10.0"
