source ./config.sh


$DAEMON_INJECTIVE tx gov submit-proposal wasm-store $WASM_INJECTIVE_STAKING_PLATFORM \
  --title "$TITLE_INJECTIVE_STAKING_PLATFORM" \
  --description "$DESCRIPTION_INJECTIVE_STAKING_PLATFORM" \
  --code-source-url $WASM_SOURCE_INJECTIVE_STAKING_PLATFORM \
	--builder $BUILDER \
	--code-hash $HASH_SUM_INJECTIVE_STAKING_PLATFORM \
  --deposit $DEPOSIT_INJECTIVE \
  --from $ADDRESS_OWNER_INJECTIVE \
  --run-as $ADDRESS_ADMIN_INJECTIVE \
  --instantiate-anyof-addresses "$ADDRESS_ADMIN_INJECTIVE,$ADDRESS_OWNER_INJECTIVE" \
  $TXFLAG_INJECTIVE
